addons:
  ssh_known_hosts: 3.137.152.55
before_install:
- openssl aes-256-cbc -K $encrypted_1a8dd2f9ae75_key -iv $encrypted_1a8dd2f9ae75_iv
  -in deploy_rsa.enc -out ./deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_1a8dd2f9ae75_key -iv $encrypted_1a8dd2f9ae75_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

install: make get-deps gcc
compiler: gcc
script: make default
deploy:
  provider: script
  skip_cleanup: true
  script: ssh ubuntu@3.137.152.55 "touch ~/myface"
  on:
    branch: master
