language: python
python:
  - "3.6"      # current default Python on Travis CI
# install dependencies
before_install:
  - sudo apt-get -y install build-essential gcc-multilib libtool automake autoconf bison debootstrap debian-archive-keyring libtool-bin gcc g++
  - sudo apt-get -y build-dep qemu
  - pip install git+https://github.com/shellphish/shellphish-afl
  - pip install git+https://github.com/shellphish/driller
  - pip install git+https://github.com/angr/tracer
  - pip install git+https://github.com/angr/phuzzer
  - gcc chall.bin.c -o chall.bin
    
# command to install dependencies
#install:
#  - pip install -r requirements.txt
# command to run tests
script:
  - travis_wait 5 python -m phuzzer -i -c 4 $(pwd)/chall
